# Upptime config - https://upptime.js.org/docs/configuration

owner: bcm-works
repo: status

sites:
  - name: bcm.works
    url: https://bcm.works/health
    icon: https://bcm.works/favicon.ico
    assignees:
      - bcm-works
  - name: murty.au
    url: https://murty.au/health
    icon: https://murty.au/favicon.ico
    assignees:
          - bcm-works

status-website:
  theme: dark
  cname: status.bcm.works
  logoUrl: https://bcm.works/images/logos/android-chrome-192x192.png
  favicon: https://bcm.works/favicon.ico
  name: Status
  introTitle: Status of bcm websites
  introMessage: Status page provided by [Upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://bcm.works
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

user-agent: bcm-works

commitMessages:
  commitAuthorName: "bot-uptime"
  commitAuthorEmail: "brendan+bot-uptime@bcm.works"
  readmeContent: "Update summary in docs"
  summaryJson: "Update status summary"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms)"
  graphsUpdate: "Update graphs"
