# Upptime config - https://upptime.js.org/docs/configuration

owner: bcm-works
repo: status

sites:
  - name: bcm.works
    url: https://bcm.works/health
    icon: https://bcm.works/favicon.ico
    assignees:
      - bcm-works
  - name: murty.au
    url: https://murty.au/health
    icon: https://murty.au/favicon.ico
    assignees:
      - bcm-works

status-website:
  name: bcm.works
  cname: status.bcm.works
  introTitle: Status
  introMessage: Website availability summary
  logoUrl: https://bcm.works/images/logos/android-chrome-192x192.png
  favicon: https://bcm.works/favicon.ico
  theme: dark
  css: ":root { --body-background-color: #000; --nav-border-bottom-color: transparent; }"
  navbar:
    - title: bcm.works
      href: https://bcm.works/
    - title: murty.au
      href: https://murty.au/
  metaTags:
    - name: "robots"
      content: "noindex"

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

user-agent: bcm-works

commitMessages:
  commitAuthorName: "Status Bot"
  commitAuthorEmail: "github@bcm.works"
  readmeContent: "Update summary in docs"
  summaryJson: "Update status summary"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms)"
  graphsUpdate: "Update graphs"
